Repository codestates-seb/seb40_main_005, pull requests merged in 2022-11, with the labels that each got.

#22 Feature/jungsoyi/board#1
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/ServerApplication.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardPatchDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardPostDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/SingleResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/mapper/BoardMapper.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/global/auditing/BaseTimeEntity.java
Labels: 🐳 BE, Board

#29 Feature/dg/security
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/global/SecurityConfig.java
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtAuthenticationEntryPoint.java
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtRequestFilter.java
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtUtils.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: 🐳 BE

#32 Feature/dg/create members
  server/src/main/java/com/gallendar/gradle/server/global/SecurityConfig.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/LoginRequest.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/LoginResponse.java
  server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
  server/src/main/resources/application.yml
Labels: 🐳 BE

#33 Feature/jungsoyi/board#2
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/ServerApplication.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardPatchDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardPostDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/SingleResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/repository/BoardRepository.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/service/CreateBoardService.java
  server/src/main/java/com/gallendar/gradle/server/domain/photo/controller/PhotoController.java
  server/src/main/java/com/gallendar/gradle/server/domain/photo/entity/Photo.java
  server/src/main/java/com/gallendar/gradle/server/domain/photo/service/PhotoService.java
  server/src/main/java/com/gallendar/gradle/server/global/auditing/BaseTimeEntity.java
  server/src/main/resources/application.yml
  server/src/test/java/com/gallendar/gradle/server/domain/board/controller/BoardControllerTest.java
  server/src/test/java/com/gallendar/gradle/server/domain/board/repository/BoardRepositoryTest.java
Labels: 🐳 BE, Board

#40 Feature/jungsoyi/board#3
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardCreateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardPostDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardUpdateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/SingleResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepository.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardPatchDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/dto/BoardResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/domain/board/service/CreateBoardService.java
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtAuthenticationEntryPoint.java
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtRequestFilter.java
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtUtils.java
  server/src/main/java/com/gallendar/gradle/server/photo/controller/PhotoController.java
  server/src/main/java/com/gallendar/gradle/server/photo/entity/Photo.java
  server/src/main/java/com/gallendar/gradle/server/photo/service/PhotoService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/gallendar/gradle/server/domain/board/controller/BoardControllerTest.java
  server/src/test/java/com/gallendar/gradle/server/domain/board/repository/BoardRepositoryTest.java
Labels: 🐳 BE, Board

#47 Feature/dg/elastic search#1
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtRequestFilter.java
  server/src/main/java/com/gallendar/gradle/server/global/config/QuerydslConfig.java
  server/src/main/java/com/gallendar/gradle/server/global/config/SecurityConfig.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/MemberSearchResponse.java
  server/src/main/java/com/gallendar/gradle/server/members/service/MemberSearchService.java
  server/src/main/resources/application.yml
Labels: 🐳 BE

#56 Feature/dg/member search by id
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/members/domain/Members.java
  server/src/test/java/com/gallendar/gradle/server/member/MemberSearchTest.java
Labels: 🐳 BE

#124 Feature/jungsoyi/board#5
  .DS_Store
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/ServerApplication.java
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/photo/config/AwsConfig.java
  server/src/main/java/com/gallendar/gradle/server/photo/config/MockS3Config.java
  server/src/main/java/com/gallendar/gradle/server/photo/config/ProcessUtils.java
  server/src/main/java/com/gallendar/gradle/server/photo/controller/PhotoController.java
  server/src/main/java/com/gallendar/gradle/server/photo/entity/Photo.java
  server/src/main/java/com/gallendar/gradle/server/photo/service/PhotoService.java
  server/src/main/java/com/gallendar/gradle/server/photo/service/S3UploadService.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: 🐳 BE, Board

#128 ✨ Feature/ eunbi/ Top 버튼 구현 #62
  client/components/topBtn.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#129 Feature/dg/tags#129
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/Members.java
  server/src/main/java/com/gallendar/gradle/server/tags/controller/TagsController.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTags.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTagsRepository.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTagsRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/Tags.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/TagsRepository.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/TagsRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/TagsRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/tags/dto/NotificationResponse.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
  server/src/test/java/com/gallendar/gradle/server/board/AddPostTest.java
  server/src/test/java/com/gallendar/gradle/server/board/RelationMappingTest.java
  server/src/test/java/com/gallendar/gradle/server/board/controller/BoardControllerTest.java
  server/src/test/java/com/gallendar/gradle/server/board/repository/BoardRepositoryTest.java
  server/src/test/java/com/gallendar/gradle/server/member/createMemberServiceTest/CreateMemberServiceTest.java
  server/src/test/java/com/gallendar/gradle/server/member/membersControllerTest/MembersControllerTest.java
Labels: 🐳 BE

#132 ✨ Feature/sunghun/랜딩페이지 퍼블리싱 완료 #57
  client/pages/index.tsx
  client/public/images/lending_네번째이미지.png
  client/public/images/lending_다섯번째이미지.png
  client/public/images/lending_두번째이미지.png
  client/public/images/lending_세번째이미지.png
  client/public/images/logo export(orange).svg
  client/public/images/logo export(white).svg
  client/public/images/solid_background.png
  client/public/images/첫화면이미지.png
  client/styles/globals.css
Labels: 🦄 FE

#136 Feature/yw/랜딩페이지 스크롤 텍스트 애니메이션 구현 #60
  client/components/scrollImg.tsx
  client/pages/index.tsx
Labels: 🦄 FE

#141 Feature/dg/notification#141
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepository.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/exception/Message.java
  server/src/main/java/com/gallendar/gradle/server/exception/Status.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/Members.java
  server/src/main/java/com/gallendar/gradle/server/tags/controller/TagsController.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/Tags.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/TagsRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/tags/dto/NotificationResponse.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
  server/src/main/java/com/gallendar/gradle/server/tags/type/TagStatus.java
  server/src/test/java/com/gallendar/gradle/server/board/NotificationTest.java
  server/src/test/java/com/gallendar/gradle/server/board/RelationMappingTest.java
Labels: 🐳 BE

#142 📈 add : swagger#142
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/global/config/SecurityConfig.java
  server/src/main/java/com/gallendar/gradle/server/global/config/SwaggerConfig.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/AuthenticationController.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/LoginResponse.java
  server/src/main/java/com/gallendar/gradle/server/tags/controller/TagsController.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
Labels: 🐳 BE

#148 🎨 add : category#148
  server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/CategoryRepository.java
Labels: 🐳 BE

#150 ♻️ refactor : lazy loading#150
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/tags/controller/TagsController.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTags.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
Labels: 🐳 BE

#151 🐛 fixed : member search 코드에 오류가 있는 부분을 수정#151
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/service/MemberSearchService.java
Labels: 🐳 BE

#152 ♻️ refactor : 연관관계 편의 메소드 수정#152
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTags.java
Labels: 🐳 BE

#155 Feature/dg/find#155
  server/src/main/java/com/gallendar/gradle/server/exception/Message.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepository.java
  server/src/main/java/com/gallendar/gradle/server/members/service/MemberSearchService.java
  server/src/test/java/com/gallendar/gradle/server/member/MemberSearchTest.java
Labels: 🐳 BE

#156 ♻️ refactor : 순환 참조 오류 해결
  server/src/main/java/com/gallendar/gradle/server/members/service/CreateMemberService.java
  server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
Labels: 🐳 BE

#157 ✨ Feature/ yw/ 랜딩페이지 하단 문구 스크롤에 따른 변화 구현 #60
  client/components/scrollImg.tsx
Labels: 🦄 FE

#158 ✨ Feature/eunbi/ index파일 및 Dots파일 수정#59
  client/components/Dots.tsx
  client/pages/index.tsx
Labels: 🦄 FE

#159 🐛 Fixed/sunghun/git merge 간 충돌해결#61
  client/pages/index.tsx
  client/pages/usage.tsx
  client/public/images/사용설명서 이미지.png
  client/public/images/사용설명서 이미지2.png
Labels: 🦄 FE

#162 ✨ Feature/yw/tailwind.config색 추가 인증페이지 외곽구현중/ #82
  client/components/CertifyPageLayout.tsx
  client/components/scrollImg.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#163 🐛Feature/sunghun/인증페이지 회원가입구현#86
  client/pages/index.tsx
  client/pages/usage.tsx
Labels: 🦄 FE

#167 Feature/dg/logout
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtRequestFilter.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/AuthenticationController.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/service/CreateMemberService.java
  server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
Labels: 🐳 BE

#169 🐛Fixed/sunghun/색상코드 중복이슈 해결#86
  client/tailwind.config.js
Labels: 🦄 FE

#171 Feature/dg/board search
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/exception/Message.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/FindIdByEmailResponse.java
  server/src/main/java/com/gallendar/gradle/server/members/service/MemberSearchService.java
Labels: 🐳 BE

#172 ✨ Feature/ yw/ 인증페이지 레이아웃 구현 완료/ #82
  client/components/CertifyPageLayout.tsx
  client/components/ConfirmBtn.tsx
  client/components/GoogleBtn.tsx
  client/components/KakaoBtn.tsx
  client/components/SubmitBtn.tsx
  client/components/WelcomeModal.tsx
  client/package-lock.json
  client/package.json
  client/pages/index.tsx
  client/pages/usage.tsx
  client/public/images/시계누끼.png
  client/tailwind.config.js
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtRequestFilter.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/AuthenticationController.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/service/CreateMemberService.java
  server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
Labels: 🦄 FE

#174 🐛 Fixed/yw/ 병합 충돌 해결
  client/package-lock.json
  client/pages/findId.tsx
  client/pages/signUp.tsx
  client/pages/usage.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#175 🐛Fixed/sunghun/merge간 충돌 해결 2차
  client/package-lock.json
  client/pages/signUp.tsx
  client/pages/usage.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#176 🐛Fixed/yw/ 병합 충돌 해결 3차
  client/package-lock.json
  client/pages/signUp.tsx
  client/pages/usage.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#177 🐛Fixed/yw/ 병합 충돌 해결 4차
  client/components/ConfirmBtn.tsx
  client/components/GoogleBtn.tsx
  client/components/KakaoBtn.tsx
  client/components/SubmitBtn.tsx
  client/components/WelcomeModal.tsx
Labels: 🦄 FE

#178 🐛Fixed/sunghun/충돌해결
  client/package-lock.json
  client/pages/signUp.tsx
  client/pages/usage.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#184 ✨Feature/sunghun/인증페이지 회원가입 id 검증 로직 구현#86
  client/apis/user/getUserId.tsx
  client/pages/signUp.tsx
Labels: 🦄 FE

#180 ✨ Feature/ yw/ 아이디 확인 기능 구현 및 CSS수정 /#88
  client/apis/user/getIdByEmail.tsx
  client/components/CertifyPageLayout.tsx
  client/pages/findId.tsx
Labels: 🦄 FE

#187 ✨Feature/sunghun/인증페이지 회원가입구현#86
  client/apis/user/checkEmail.tsx
  client/apis/user/checkUserId.tsx
  client/components/AuthBtn.tsx
  client/components/EmailCheckNumberLayout.tsx
  client/hooks/user/useCheckEmail.tsx
  client/hooks/user/useCheckUserId.tsx
  client/pages/signUp.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#189 🐛Fiexed/sunghun/git merge 간 충돌해결#86
  client/apis/user/checkEmail.tsx
  client/apis/user/checkUserId.tsx
  client/components/AuthBtn.tsx
  client/components/EmailCheckNumberLayout.tsx
  client/hooks/user/useCheckEmail.tsx
  client/hooks/user/useCheckUserId.tsx
  client/pages/signUp.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#191 🐛fixed/sunghun/merge 충돌해결#86
  client/apis/user/getUserId.tsx
  client/pages/signUp.tsx
  client/tailwind.config.js
Labels: 🦄 FE

#193 🐛Fixed/yw/ 병합충돌해결
  client/pages/signUp.tsx
Labels: 🦄 FE

#195 :sparkles: 사진, 게시글 연관관계 설정. 사진 DB 설정
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/photo/config/MockS3Config.java
  server/src/main/java/com/gallendar/gradle/server/photo/controller/PhotoController.java
  server/src/main/java/com/gallendar/gradle/server/photo/dto/PhotoCreateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/photo/repository/PhotoRepository.java
  server/src/main/java/com/gallendar/gradle/server/photo/service/S3UploadService.java
  server/src/main/resources/application.yml
Labels: 🐳 BE, Board

#196 ♻️ refactor / eunbi / SubmitBtn 코드 수정 #87
  client/components/SubmitBtn.tsx
Labels: 🦄 FE

#198 ✨ Feature/ eunbi/ login 기능 구현(미완) #87
  client/apis/auth/postLogin.tsx
  client/components/LoginForm.tsx
  client/hooks/auth/useLogin.tsx
  client/pages/login.tsx
  client/pages/signUp.tsx
  client/recoil/authAtom.ts
  client/recoil/authAtom.tsx
Labels: 🦄 FE

#199 ✨Feature/sunghun/인증페이지 회원가입구현#86
  client/apis/user/checkAuthNum.tsx
  client/apis/user/postSignUp.tsx
  client/hooks/user/useCheckAuthNum.tsx
  client/pages/signUp.tsx
Labels: 🦄 FE

#201 Feature/dg/board search#201
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchResponse.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
  server/src/main/java/com/gallendar/gradle/server/tags/dto/NotificationResponse.java
  server/src/test/java/com/gallendar/gradle/server/board/BoardSearchTest.java
Labels: 🐳 BE

#204 :white_check_mark: test : board api test
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/service/CreateMemberService.java
  server/src/main/java/com/gallendar/gradle/server/members/service/SendEmail.java
  server/src/test/java/com/gallendar/gradle/server/board/controller/BoardControllerTest.java
  server/src/test/java/com/gallendar/gradle/server/membersControllerTest/MembersControllerTest.java
Labels: 🐳 BE, Board, TEST

#205 ✨ Feature / eunbi/ login 기능 구현#87
  client/components/LoginForm.tsx
  client/pages/login.tsx
Labels: 🌝 회고

#209 ✨Feature/sunghun/인증페이지 회원가입구현#86
  client/apis/user/checkAuthNum.tsx
  client/apis/user/postSignUp.tsx
  client/hooks/user/useCheckAuthNum.tsx
  client/hooks/user/usePostSignUpData.tsx
  client/pages/signUp.tsx
Labels: 🦄 FE

#212 🐛 Fixed/sunghun/인증요청 버튼 로직 수정
  client/pages/signUp.tsx
Labels: 🦄 FE

#213 Feature/dg/patchpassword#213
  server/src/main/java/com/gallendar/gradle/server/global/auth/encoder/CommonEncoder.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/AuthenticationController.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/Members.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/ChangePasswordRequest.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/ChangePasswordResponse.java
  server/src/main/java/com/gallendar/gradle/server/members/dto/LoginResponse.java
  server/src/main/java/com/gallendar/gradle/server/members/service/ChangePasswordService.java
  server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
Labels: 🐳 BE

#216 ✨Feature/sunghun/인증페이지 회원가입구현#86
  client/components/ConfirmBtn.tsx
  client/components/WelcomeModal.tsx
  client/pages/signUp.tsx
Labels: 🦄 FE

#220 🐛 fixed : bug#220
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
Labels: 🐳 BE

#221 ✨ Feature/yw/비밀번호 변경 기능구현 완료#89
  client/apis/user/petchPassword.tsx
  client/components/ResetPwModal.tsx
  client/hooks/user/usePatchPw.tsx
  client/pages/resetPw.tsx
Labels: 🦄 FE

#222 ✨ Feature / eunbi/ calendar 초기 레이아웃 수정 및 Nav 구현#69
  client/components/CalendarContainer.tsx
  client/components/CalendarNav.tsx
  client/components/CalendarPageLayout.tsx
Labels: 🦄 FE

#223 🐛 Fixed/sunghun/페이지 이름 수정 및 Link 재설정
  client/components/CertifyPageLayout.tsx
  client/components/LoginForm.tsx
  client/pages/findid.tsx
  client/pages/index.tsx
  client/pages/mypage.tsx
  client/pages/resetpw.tsx
  client/pages/signup.tsx
  client/pages/usage.tsx
Labels: 🦄 FE

#228 Feature/sunghun/인증페이지 회원가입구현#86
  client/apis/auth/checkAuthNum.tsx
  client/apis/auth/postAuthNum.tsx
  client/apis/user/checkAuthNum.tsx
  client/apis/user/checkEmail.tsx
  client/apis/user/checkUserId.tsx
  client/components/Dots.tsx
  client/components/LoginForm.tsx
  client/components/ScrollImg.tsx
  client/components/TopBtn.tsx
  client/hooks/user/useCheckAuthNum.tsx
  client/hooks/user/useRequestAuthNum.tsx
  client/pages/index.tsx
  client/pages/signup.tsx
  client/pages/usage.tsx
Labels: 🦄 FE

#233 ✨Feature/sunghun/캘린더페이지 side bar구현#78
  client/components/CalendarPageLayout.tsx
  client/components/Sidebar.tsx
Labels: 🦄 FE

#234 ✨ Feature/ eunbi/ calendar 초기 작업 및 date-fns#79
  client/components/CalendarContainer.tsx
  client/components/TodayBtn.tsx
  client/package-lock.json
  client/package.json
  client/tailwind.config.js
Labels: 🦄 FE

#235 Feature/sunghun/날짜설정기능구현#66
  client/components/CalendarContainer.tsx
  client/components/DayInput.tsx
  client/components/LeftBtn.tsx
  client/components/RightBtn.tsx
  client/components/TodayBtn.tsx
Labels: 🦄 FE

#236 Feature/jungsoyi/test
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardCreateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardUpdateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/board/mapper/BoardMapper.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/photo/controller/PhotoController.java
  server/src/main/java/com/gallendar/gradle/server/photo/service/S3UploadService.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTags.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/TagsRepository.java
  server/src/main/java/com/gallendar/gradle/server/tags/dto/TagsCreateDto.java
Labels: 🐳 BE, Board

#237 Feature/dg/board search
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchResponse.java
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
  server/src/main/java/com/gallendar/gradle/server/global/auth/jwt/JwtUtils.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/Tags.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
  server/src/main/java/com/gallendar/gradle/server/tags/type/TagStatus.java
Labels: 🐳 BE

#238 Feature/dg/board search by id#238
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchByIdResponse.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
  server/src/test/java/com/gallendar/gradle/server/board/BoardSearchTest.java
Labels: 🐳 BE

#239 ✨ Feature/ yw/ 비밀번호 재설정api연결 / #89
  client/apis/user/petchPassword.tsx
  client/hooks/user/usePatchPw.tsx
  client/pages/resetpw.tsx
Labels: 🦄 FE

#240 ✨ Feature/yw/인증페이지레이아웃 컴포넌트JSdocs작성 및 랜딩 하단 스크롤 수정 #82
  client/components/CertifyPageLayout.tsx
  client/components/ScrollImg.tsx
Labels: 🦄 FE

#241 Feature/dg/tag member condition#241
  server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/tags/controller/TagConditionController.java
  server/src/main/java/com/gallendar/gradle/server/tags/dto/CountBoardResponse.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/TagService.java
  server/src/test/java/com/gallendar/gradle/server/board/TagConditionTest.java
Labels: 🐳 BE

#242 :recycle: tags 수정
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTagsRepository.java
Labels: 🐳 BE, Tags

#243 :art: improve : tag 수정, 사용자 검증 추가
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardUpdateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
Labels: 🐳 BE, Board, Tags

#244 :sparkles: category 등록, 수정 구현
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardUpdateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/CategoryRepository.java
  server/src/main/java/com/gallendar/gradle/server/category/dto/CategoryCreateDto.java
  server/src/main/java/com/gallendar/gradle/server/category/service/CategoryService.java
Labels: 🐳 BE, Board, Category

#245 Feature/dg/logback#245
  server/build.gradle
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/AuthenticationController.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/service/ChangePasswordService.java
  server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
  server/src/main/java/com/gallendar/gradle/server/members/service/MemberSearchService.java
  server/src/main/java/com/gallendar/gradle/server/tags/controller/TagConditionController.java
  server/src/main/java/com/gallendar/gradle/server/tags/controller/TagsController.java
  server/src/main/java/com/gallendar/gradle/server/tags/dto/NotificationResponse.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
  server/src/main/resources/logback.xml
Labels: 🐳 BE

#246 ✨Feature/sunghun/모달레이아웃구현#70
  client/components/BoardContainer.tsx
  client/components/CalendarPageLayout.tsx
Labels: 🦄 FE

#247 ✨ Feature / eunbi / 환경변수 세팅#79
  client/.gitignore
  client/client/client.tsx
Labels: 🦄 FE

#248 ✨Feature/sunghun/게시글작성모달구현#80
  client/apis/auth/checkAuthNum.tsx
  client/apis/auth/postAuthNum.tsx
  client/apis/auth/postLogin.tsx
  client/apis/user/checkEmail.tsx
  client/apis/user/checkUserId.tsx
  client/apis/user/getIdByEmail.tsx
  client/apis/user/getUserId.tsx
  client/apis/user/petchPassword.tsx
  client/apis/user/postSignUp.tsx
  client/components/CalendarPageLayout.tsx
  client/components/CategoryInputContainer.tsx
  client/components/CreateModalLayout.tsx
Labels: 🦄 FE

#250 Feature/jungsoyi/tag
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/CategoryRepository.java
  server/src/main/java/com/gallendar/gradle/server/category/dto/CategoryCreateDto.java
  server/src/main/java/com/gallendar/gradle/server/category/service/CategoryService.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/BoardTagsRepository.java
  server/src/main/java/com/gallendar/gradle/server/tags/type/TagStatus.java
Labels: 🐳 BE, Board, Tags, Category

#251 Feature/dg/parameters
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardCreateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardUpdateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/category/controller/CategoryController.java
  server/src/main/java/com/gallendar/gradle/server/category/service/ReadCategoryService.java
Labels: 🐳 BE

#252 ✨ Feature / eunbi / calendar 레이아웃 구현#79
  client/components/AddBtn.tsx
  client/components/CalendarBody.tsx
  client/components/DayBlock.tsx
  client/components/PlusImg.tsx
  client/package-lock.json
  client/package.json
  client/tailwind.config.js
Labels: 🦄 FE

#256 ✨ Feature/ yw/ 카테고리 태그 레이아웃 구현 /#65
  client/components/Sidebar.tsx
  client/components/SidebarCategory.tsx
Labels: 🦄 FE

#255 ✨Feature/sunghun/게시글작성모달구현#80
  client/components/AddMusicContainer.tsx
  client/components/AddPhoto.tsx
  client/components/AddPhotoContainer.tsx
  client/components/BoardContainer.tsx
  client/components/BoardModalBtn.tsx
  client/components/BoardModalContainer.tsx
  client/components/CalendarPageLayout.tsx
  client/components/CategoryInputContainer.tsx
  client/components/CreateModalLayout.tsx
  client/components/HeadPhone.tsx
  client/components/LeftArrow.tsx
Labels: 🦄 FE

#257 Feature/sunghun/게시글작성모달구현#80
  client/components/AddMusicContainer.tsx
  client/components/AddPhotoContainer.tsx
  client/components/AddShareContainer.tsx
  client/components/AddTextContainer.tsx
  client/components/CreateModalLayout.tsx
  client/components/Search.tsx
  client/public/images/search.svg
Labels: 🦄 FE

#260 :bug: category 수정
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/CategoryRepository.java
  server/src/main/java/com/gallendar/gradle/server/photo/service/S3UploadService.java
Labels: 🐳 BE, Board, Tags, Category

#261 Feature/dg/board
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardUpdateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/category/domain/Category.java
  server/src/main/java/com/gallendar/gradle/server/tags/type/TagStatus.java
  server/src/test/java/com/gallendar/gradle/server/board/AddPostTest.java
  server/src/test/java/com/gallendar/gradle/server/board/BoardUpdateTest.java
  server/src/test/java/com/gallendar/gradle/server/createMemberServiceTest/CreateMemberServiceTest.java
  server/src/test/java/com/gallendar/gradle/server/member/MemberSearchTest.java
  server/src/test/java/com/gallendar/gradle/server/member/createMemberServiceTest/CreateMemberServiceTest.java
  server/src/test/java/com/gallendar/gradle/server/member/membersControllerTest/MembersControllerTest.java
  server/src/test/java/com/gallendar/gradle/server/membersControllerTest/MembersControllerTest.java
  server/src/test/java/com/gallendar/gradle/server/tags/FindByTagMembersTest.java
Labels: 🐳 BE

#264 ✨Feature/sunghun/게시글작성모달 음악UI개편#258
  client/components/AddMusicContainer.tsx
  client/components/BoardContainer.tsx
  client/components/BoardModalBtn.tsx
  client/components/CreateModalLayout.tsx
  client/components/HeadPhone.tsx
  client/components/YoutubeIcon.tsx
Labels: 🦄 FE

#262 ✨ Feature/ yw/ 사이드바 카테고리구현 완료/ #65
  client/components/Sidebar.tsx
  client/components/SidebarCategory.tsx
Labels: 🦄 FE

#265 🐛 fixed : querydsl error#265
  server/.gitignore
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
Labels: 🐳 BE

#267 Feature/dg/board#267
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardCreateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardListResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchByIdResponse.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchResponse.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardUpdateRequestDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/MultiResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/PageInfo.java
  server/src/main/java/com/gallendar/gradle/server/board/entity/Board.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardService.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardServiceImpl.java
  server/src/main/java/com/gallendar/gradle/server/members/service/LoginService.java
Labels: 🐳 BE

#268 :construction_worker: CI/CD 위한 deploy.sh 파일 생성
  server/$buildDir/generated/querydsl/com/gallendar/gradle/server/board/entity/QBoard.java
  server/$buildDir/generated/querydsl/com/gallendar/gradle/server/category/domain/QCategory.java
  server/$buildDir/generated/querydsl/com/gallendar/gradle/server/global/auditing/QBaseTimeEntity.java
  server/$buildDir/generated/querydsl/com/gallendar/gradle/server/members/domain/QMembers.java
  server/$buildDir/generated/querydsl/com/gallendar/gradle/server/photo/entity/QPhoto.java
  server/$buildDir/generated/querydsl/com/gallendar/gradle/server/tags/domain/QBoardTags.java
  server/$buildDir/generated/querydsl/com/gallendar/gradle/server/tags/domain/QTags.java
  server/scripts/deploy.sh
Labels: 🐳 BE

#269 🎨 fixed : notification accept
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/NotificationService.java
  server/src/test/java/com/gallendar/gradle/server/board/controller/BoardControllerTest.java
  server/src/test/java/com/gallendar/gradle/server/tags/FindByTagMembersTest.java
Labels: 🐳 BE

#271 ✨ Feature/ yw/ 카테고리 api연결중 / #65
  client/apis/user/getCtegoryTitle.tsx
  client/apis/user/getIdByEmail.tsx
  client/components/Sidebar.tsx
  client/components/SidebarCategory.tsx
  client/hooks/user/useGetCategoryTltie.tsx
Labels: 🦄 FE

#273 ✨ Feature/sunghun/api 훅으로 전환 및 보안설정
  client/apis/auth/checkAuthNum.tsx
  client/apis/auth/postAuthNum.tsx
  client/apis/auth/postLogin.tsx
  client/apis/user/checkEmail.tsx
  client/apis/user/checkUserId.tsx
  client/apis/user/getIdByEmail.tsx
  client/apis/user/getUserId.tsx
  client/apis/user/petchPassword.tsx
  client/apis/user/postSignUp.tsx
  client/client/client.tsx
  client/components/AddBtn.tsx
  client/components/AddMusicContainer.tsx
  client/components/AddTextContainer.tsx
  client/components/CalendarPageLayout.tsx
  client/components/CreateModalLayout.tsx
  client/components/DayBlock.tsx
  client/next.config.js
  client/pages/calendar.tsx
  client/recoil/authAtom.ts
  client/recoil/calendarAtom.tsx
Labels: 🦄 FE

#275 ✨ Feature/ eunbi/ 이미지 업로드 관련 코드수정
  client/components/AddPhotoContainer.tsx
  client/components/CalendarContainer.tsx
  client/components/CreateModalLayout.tsx
Labels: 🦄 FE

#274 ✨ Feature/sunghun/+버튼 클릭 시 해당 날짜코드 받아오기 완료
  client/components/CalendarBody.tsx
  client/components/CalendarPageLayout.tsx
  client/components/CreateModalLayout.tsx
  client/components/DayBlock.tsx
  client/recoil/calendarAtom.tsx
Labels: 🦄 FE

#277 Feature/jungsoyi/cicd #277
  server/.gitignore
  server/src/main/java/com/gallendar/gradle/server/deploy/DeployTest.java
  server/src/main/resources/application.yml
Labels: 🐳 BE

#278 🐛 : 카테고리 목록 조회 중복제거 #278
  server/src/main/java/com/gallendar/gradle/server/category/controller/CategoryController.java
  server/src/main/java/com/gallendar/gradle/server/category/dto/CategoryListResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/category/service/CategoryService.java
Labels: 🐳 BE

#279 ✨ Feature / eunbi/ 게시글타이틀 컨테이너 구현
  client/components/CalendarPageLayout.tsx
  client/components/LoginForm.tsx
  client/components/MyBoard.tsx
  client/components/SharedBoard.tsx
  client/recoil/authAtom.ts
Labels: 🦄 FE

#280 ✨ Feature/sunghun/캘린더페이지 게시글작성모달구현#80
  client/apis/board/postBoardData.tsx
  client/components/CreateModalLayout.tsx
  client/hooks/calendar/usePostBoard.tsx
Labels: 🦄 FE

#281 Feature/dg/quit#281
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/board/repository/BoardRepositoryCustomImpl.java
  server/src/main/java/com/gallendar/gradle/server/global/config/SecurityConfig.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersController.java
  server/src/main/java/com/gallendar/gradle/server/members/controller/MembersQuitController.java
  server/src/main/java/com/gallendar/gradle/server/members/service/QuitMemberService.java
  server/src/main/java/com/gallendar/gradle/server/tags/domain/Tags.java
  server/src/main/java/com/gallendar/gradle/server/tags/type/TagStatus.java
  server/src/test/java/com/gallendar/gradle/server/board/QuitMemberTest.java
Labels: 🐳 BE

#282 ✨ Feature/ eunbi/ 캘린더 특정 날짜에 게시글 조회기능구현#276
  client/apis/board/getBoards.tsx
  client/apis/board/getCategory.tsx
  client/client/client.tsx
  client/components/CalendarBody.tsx
  client/components/CalendarContainer.tsx
  client/components/CalendarPageLayout.tsx
  client/components/CertifyPageLayout.tsx
  client/components/CreateModalLayout.tsx
  client/components/DayBlock.tsx
  client/components/MyBoard.tsx
  client/components/SharedBoard.tsx
  client/components/Sidebar.tsx
  client/hooks/calendar/useGetBoards.tsx
  client/hooks/calendar/useGetCategory.tsx
  client/pages/calendar.tsx
  client/pages/signup.tsx
Labels: 🦄 FE

#283 ✨Feature/sunghun/게시글작성모달 api연결 완료
  client/apis/board/postBoardData.tsx
  client/client/formClient.tsx
  client/components/AddPhotoContainer.tsx
  client/components/CalendarPageLayout.tsx
  client/components/CreateModalLayout.tsx
  client/components/DayBlock.tsx
  client/hooks/calendar/usePostBoard.tsx
  client/recoil/calendarAtom.tsx
Labels: 🦄 FE

#285 🐛 카테고리 목록 조회 메인페이지/ 게시글 작성 페이지
  server/src/main/java/com/gallendar/gradle/server/category/controller/CategoryController.java
  server/src/main/java/com/gallendar/gradle/server/category/dto/AllCategoryListResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/category/dto/CategoryListResponseDto.java
  server/src/main/java/com/gallendar/gradle/server/category/service/AllCategoryListService.java
Labels: 🐳 BE

#284 ✨ Feature/ yw/ 캘린더 화면 카테고리 구현 완료/ #65
  client/apis/user/getCtegoryTitle.tsx
  client/components/Sidebar.tsx
  client/hooks/user/useGetCategoryTltie.tsx
Labels: 🦄 FE

#286 ✨ feat : 게시글 작성 여부 반환#286
  server/src/main/java/com/gallendar/gradle/server/board/controller/BoardController.java
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardCountResponse.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardCountService.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustom.java
  server/src/main/java/com/gallendar/gradle/server/members/domain/MembersRepositoryCustomImpl.java
  server/src/test/java/com/gallendar/gradle/server/board/CountBoardTest.java
  server/src/test/java/com/gallendar/gradle/server/board/QuitMemberTest.java
Labels: 🐳 BE

#287 🎨 fixed : boardSearchResponse 응답 수정
  server/src/main/java/com/gallendar/gradle/server/board/dto/BoardSearchResponse.java
  server/src/main/java/com/gallendar/gradle/server/board/service/BoardSearchService.java
Labels: 🐳 BE

#288 ✨ Feature/ eunbi/ 알림 모달 레이아웃 작업
  client/components/CalendarBody.tsx
  client/components/CreateModalLayout.tsx
  client/components/DayBlock.tsx
  client/components/MyBoard.tsx
  client/components/Sidebar.tsx
  client/components/noticeLayout.tsx
  client/hooks/calendar/usePostBoard.tsx
Labels: 🦄 FE

#289 ✨ Feature/yw/ 카테고리 api연결 주석 정리/ #65
  client/components/Sidebar.tsx
Labels: 🦄 FE

#290 ✨Feature/sunghun/git충돌 긴급수정
  client/components/CreateModalLayout.tsx
Labels: 🦄 FE

#291 🎨 fixed : 유저의 태그 된 게시글 개수 응답
  server/src/main/java/com/gallendar/gradle/server/tags/dto/CountBoardResponse.java
  server/src/main/java/com/gallendar/gradle/server/tags/service/TagService.java
  server/src/test/java/com/gallendar/gradle/server/board/repository/BoardRepositoryTest.java
Labels: 🐳 BE
